const ACTION_TYPES = {
  'SIGN_IN': 'SIGN_IN',
  'SIGN_IN_SUCCESS': 'SIGN_IN_SUCCESS',
  'SIGN_IN_ERROR': 'SIGN_IN_ERROR',
  'GET_USER_LIST': 'GET_USER_LIST',
  'GET_USER_LIST_SUCCESS': 'GET_USER_LIST_SUCCESS',
  'GET_USER_LIST_ERROR': 'GET_USER_LIST_ERROR',
  'CLEAR_GET_USER_LIST': 'CLEAR_GET_USER_LIST',
  'GET_USER_DETAIL': 'GET_USER_DETAIL',
  'GET_USER_DETAIL_SUCCESS': 'GET_USER_DETAIL_SUCCESS',
  'GET_USER_DETAIL_ERROR': 'GET_USER_DETAIL_ERROR',
  'CLEAR_GET_USER_DETAIL': 'CLEAR_GET_USER_DETAIL',
};

export default ACTION_TYPES;
